### PR TITLE
Add source to the download links

### PR DESCRIPTION
**Pull request by DMarby**
This allows the API to track whether a download comes from the website or the app autoupdater

### CODE REVIEW

**Review by develohpanda — CHANGES_REQUESTED** [review]
👍 I suggest some refactoring in order to de-duplicate the links. It's effectively a static resource, to which a `ref` query param is sometimes added. If one link changes, all should change, so I don't particularly like that each link is copy-pasted three times in the same code-base.

It looks like the `LINKS` variable in `direct-download-button` was heading down that path already, so we can probably take it one step further now that this area of code is being looked at.

**Comment by DMarby** [comment]
While I generally I agree with improving code as we're touching it, that is out of scope for this PR, so I will not be making any such changes in this PR.

**Review by develohpanda — APPROVED** [review]
In that case, could you please create a ticket in Linear to address it in the future, or create a separate PR?

**Comment by DMarby** [comment]
As this is getting replaced by the new marketing website shortly, and even if it wasn't, such a refactoring is an extremely low priority task with negligible benefits, and I will not be doing either of those things, no.

**Comment by DMarby** [comment]
As this will be getting replaced by the new marketing website in the near future, we will not be refactoring any of this code, so I will not be doing so, no.

**Pull request merged**
